name: Compass
version: 1.12.0
main: Compass\CompassBar
api: 3.0.0, 4.0.0
description: Powerful API plugin. API added by IceCruelStuff
author: IceCruelStuff
website: https://github.com/IceCruelStuff/Compass
load: STARTUP
commands:
  compass:
    description: Shows compass
    permission: compassbar
    overloads: []
    
permissions:
  compassbar:
    default: true
